server:
  port: 8088

spring:
  application:
    name: CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/rushi6298/microservice-tutorial-config
          clone-on-start: true
