spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rushi6298/microservice-tutorial-config
          clone-on-start: true
    configserver:
      enabled: true  # Add this to enable the config server explicitly
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
