server:
  port: 8083

spring:
  application:
    name: RATING-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/ratingsmicroservices
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
  
  config:
    import: 
      - "optional:configserver:http://localhost:8088"
    
#  eureka:
#    instance:
#      prefer-ip-address: true
#    client:
#      fetch-registry: true  
#      register-with-eureka: true
#      service-url:
#        defaultZone: http://localhost:8761/eureka
